### ISSUE TITLE
System UI failed

### ISSUE THREAD

**Issue by yovanoc** [christianalfoni/stitches#1]
Hello, there is a fail actually, the system ui doc says:

![image](https://user-images.githubusercontent.com/7302317/79360340-12e93b00-7f44-11ea-803e-678575b447f9.png)

but in stitches the padding are taken from sizes and not space

thanks

**Comment by christianalfoni** [comment]
Hi @yovanoc ! 😄 

Where do you see it is taken from `sizes`? In the source code it is using `space`?

**Comment by yovanoc** [comment]
Sorry, that's was my fault.
