### ISSUE TITLE
Wrong tailwind typing or api

### ISSUE THREAD

**Issue by yovanoc** [christianalfoni/stitches#11]
![image](https://user-images.githubusercontent.com/7302317/79871848-46fda980-83e5-11ea-8fa8-beea868ce34f.png)

Just encounter that,  we just can put `-px` and nothing else here so its a typing or api issue?

**Comment by christianalfoni** [comment]
I have this on my end now, which version you on?:

<img width="733" alt="Screenshot 2020-04-22 at 17 08 04" src="https://user-images.githubusercontent.com/3956929/79999128-d70e2280-84bb-11ea-8743-0fcc8bf090b4.png">

**Comment by yovanoc** [comment]
1.4.6 always same issue

**Comment by yovanoc** [comment]
but maybe it comes from the fact I mixed styled and tailwind?

![image](https://user-images.githubusercontent.com/7302317/80001080-4127c700-84be-11ea-94f5-a4e29e50562d.png)

**Comment by christianalfoni** [comment]
Oh, I found the issue, well two issues:

1. You can actually import from `/utils` and `/theme`, there was a couple of missing folders in the release, fixed now

2. There seems to be a bug in Typescript, where it converts `{ "-1": string }` into `{ -1: string }`, creating invalid syntax in the declaration file

Looking into number 2. now 😄

**Comment by christianalfoni** [comment]
Okay, so 2. seems to be a bug in Typescript: https://github.com/microsoft/TypeScript/issues/38133

I am having a hard time creating a workaround for this, but will let you know if I find something

**Comment by christianalfoni** [comment]
Okay, I found a workaround for now, released in latest version 😄

**Comment by yovanoc** [comment]
Yes perfect! you're good man!
