### ISSUE TITLE
Compose external `className`

### ISSUE THREAD

**Issue by peduarte** [christianalfoni/stitches#13]
Hey! 

I'm super excited about this! Having spent the last year diving deep into multiple styling approaches, this seems very promising - at a glance.

For now I have one question, I'd like to create a component with some baked in `className` but I also want to accept a class from the outside. 

For example:
```jsx
const Button = React.forwardRef<
  HTMLButtonElement,
  React.ComponentPropsWithRef<"button">
>((props, ref) => {
  return (
    <button
      ref={ref}
      className={css.compose(
        css.color("red500"),
        css.fontSize(5),
        props.className || ""
      )}
      {...props}
    />
  );
});

export default function App() {
  return (
    <div className="App">
      <Button className={css.color("blue500")}>Test</Button>
    </div>
  );
}
```

What I've tried to do is to just inject `props.className` into `css.compose` function - but seems Im going about it the wrong way.

What's happening is that the `className` I passed in works, but the previous baked in classes are gone. I expect to see a button with font size of 5 and blue. But it's just blue.

Would I need to use something like [classnames](https://www.npmjs.com/package/classnames)?

**Comment by peduarte** [comment]
Ah, turns out it works but I was spreading the props in the wrong place 😂

**Comment by lauritzsh** [comment]
This doesn't seem to work for me. I don't know if it's a Next issue or not but I get these errors

```
TypeError: cannot use 'in' operator to search for "atoms" in "MyComponent"

composeIntoMap
./node_modules/@stitches/css/es/index.js:53

  50 | var item = atoms[i];
  51 | // atoms can be undefined, null, false or '' using ternary like
  52 | // expressions with the properties
> 53 | if (item && "atoms" in item) {
  54 | ^    composeIntoMap(map, item.atoms);
  55 | }
  56 | else if (item) {

compose
./node_modules/@stitches/css/es/index.js:117

  114 |     atoms[_i] = arguments[_i];
  115 | }
  116 | var map = new Map();
> 117 | composeIntoMap(map, atoms);
  118 | return {
  119 |     atoms: Array.from(map.values()),
  120 |     toString: toStringCompose,
```

I just call it like this `className={css.compose(css.color('red'), props.className)}`. Can't really see what should be wrong.

**Comment by lauritzsh** [comment]
@peduarte How did you make this work? I want to use it like `className={css.compose(css.color('red'), props.className)}` for example but it blows up. Would be really nice if compose could be made to work with this so we don't have to use the classnames package.

**Comment by peduarte** [comment]
My issue was that I was spreading props `{...props}` after `className`, so it was essentially overriding the classes
