### ISSUE TITLE
Unable to get css.appearance to work

### ISSUE THREAD

**Issue by peduarte** [christianalfoni/stitches#17]
Hey, 

I'm not being able to get `css.appearance("none")` to work.

Here's a repro: https://codesandbox.io/s/stiches-appearance-itc5w

Not sure why but I wonder if it's something to do with browser prefixes...?

**Comment by christianalfoni** [comment]
Hi @peduarte !

Vendor prefixes was on our roadmap and is now implemented in latest version 😄
