### ISSUE TITLE
Utils require second argument by default

### ISSUE THREAD

**Issue by peduarte** [christianalfoni/stitches#18]
Taken from example in the readme, here I'm adding a `marginX` util, but I'm required to pass in a second argument (pseudo)

Repro: https://codesandbox.io/s/stiches-utils-require-second-argument-iybfq?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/372831/79883919-c3e44f80-83f4-11ea-8336-af59c5855714.png)

Is this behaving as expected?

**Comment by christianalfoni** [comment]
Ah, yeah, did not write that example with Typescript 😂 Updated in Readme now
