### ISSUE TITLE
Add examples for dynamic styles

### ISSUE THREAD

**Issue by alaister** [christianalfoni/stitches#2]
Hello,
It would be good if you could provide some examples on the best way to handle dynamic styles with stitches.

For example changing the value of a property based on a React prop.
I've been doing this: `css.flexDirection(direction === 'vertical' ? 'column' : 'row')` which seems to work.

Also some examples on including and excluding entire properties from a compose call. For example:
```javascript
const styles = css.compose(
  css.display('flex'),
  justify && css.justifyContent(justify),
  align && css.alignItems(align),
)
```
This does not seem to work, which makes me think this may not be the best approach in the first place.

Cheers

**Comment by christianalfoni** [comment]
@alaister 

All your examples work now, which is how it was intended to work, it was a bug 😄

Let me add a section on dynamic styles, thanks for the heads up!
