### ISSUE TITLE
Maximum call stack size exceeded when loggin `css` (the return of `createCss` function)

### ISSUE THREAD

**Issue by peduarte** [christianalfoni/stitches#21]
Based on the following code:

```js
const css = createCss({
  tokens: {
    colors: {
      red500: "hsl(358, 92%, 74%)"
    }
  }
});

console.log(css);
```

Repro: https://codesandbox.io/s/stiches-log-css-ft3vm?file=/src/App.tsx:99-216

**Comment by christianalfoni** [comment]
Ah, yes, dear proxies 😂 

I believe it all starts with an `inspect` property being accessed, so we can block the nesting of lookups. The thing is that none of the properties actually exist, we use a proxy to dynamically create the CSS based on the property you try to access.

But yeah, you will probably just get an empty object back there, but at least block the call stack issue would be nice 😄

**Comment by peduarte** [comment]
Ah, gotcha. 

So the reason I was trying to log it in the first place is because I was trying to understand what where the properties available to me. 

If it logged an empty object I think I would’ve been confused too.

**Comment by christianalfoni** [comment]
Jup, this is the negative side of proxies, you do not know what they proxy. The positive thing though is that it is 3 lines of code instead of thousands 😂 

But, we can return a string there instead explaining that it is a proxy and what properties are available

**Comment by peduarte** [comment]
Yeah, that makes sense 👌
