### ISSUE TITLE
TypeError: Cannot set property overflow of #<Object> which has only a getter

### ISSUE THREAD

**Issue by gsgualbano** [christianalfoni/stitches#22]
Hello, I created a react typescript project using CRA to test out this lib, but i'm getting this error when i use @stitches/tailwind

```
TypeError: Cannot set property overflow of #<Object> which has only a getter

addDefaultUtils
src/utils.ts:107

  104 | 
  105 | export const addDefaultUtils = (config: IConfig) => {
  106 |   config.utils = config.utils || {};
> 107 |   config.utils.overflow = (css) => (
  108 |     value: StandardProperties["overflow"],
  109 |     pseudo?: string
  110 |   ) =>
``` 

this is my code

```
import React from 'react';
import { createCss } from '@stitches/css';
import { tailwind } from '@stitches/tailwind';

const css = createCss(tailwind);

function App() {
  return (
    <div className="App">
      <h1 className={css.compose(css.mt(10))}>Hello World</h1>
    </div>
  );
}

export default App;
```

if i use only the css from @stitches/css it works fine, but with the tailwind version, i keep getting this error

**Comment by christianalfoni** [comment]
Hi there and thanks a bunch for the issue!

I am not sure why this happens, but it led me to see an other bug so I have changed how these default utilities are added so it fixes two issues 😄 

If you install latest it is fixed!
