### ISSUE TITLE
Ant Design support

### ISSUE THREAD

**Issue by gsgualbano** [christianalfoni/stitches#23]
Hi, i'm trying to use stitches with the ant design ui lib, but unfortunately it doesn't work.

It doesn't generate the class names properly on the Ant Design Components.

example:

my code
```
<Footer className={css.compose(css.textAlign('center'))}>
    ©2020 Created by Gustavo Gualbano
</Footer>
```

what generates:
```
<footer class="ant-layout-footer atoms toString">©2020 Created by Gustavo Gualbano</footer>
``` 

it puts this `atoms toString` on the class.

if i use on a native html element likes this

```
<div className={css.compose(css.textAlign('center'))}>
  <Footer>©2020 Created by Gustavo Gualbano</Footer>
</div>
```

works just fine, but if i use directly on a ant design component, it doesn't.

**Comment by christianalfoni** [comment]
hi @gsgualbano ,

The reason for this is that we we depend on the `toString` method of the return object to be called. This is normally called in all circumstances where a string is expected, but for some reason `ant` does not follow this convention. 

If you were to `String(css.compose(css.textAlign('center')))`, you would be okay.

You have a link to the project? We could create a PR which ensures this behaviour, as it should really work that way.

**Comment by gsgualbano** [comment]
Thank you @christianalfoni,

Wrapping the compose on a String function worked really well. I don't have a link to my project because it's just a side project that i made for studying purposes, anyway thanks again.

**Comment by christianalfoni** [comment]
Oh, I meant to Ant :-) so that we can fix the issue on their side. Glad it
worked! :-)

**Comment by gsgualbano** [comment]
lol 😂, I’m sorry I misunderstood, here is the link https://github.com/ant-design/ant-design
