### ISSUE TITLE
[feature] Calc() and other functions

### ISSUE THREAD

**Issue by CodingDive** [christianalfoni/stitches#26]
I would love to see calc and other functions. They could either be implemented as a first-class citizen of stitches. E.g `css.calc()` or alternatively, provide a string-based escape hatch for the `utilCss` to define arbitrary css.

This could allow us to define our own functions.

I'm not sure how exactly this API could look like but one idea I had was the following:

```TypeScript
type ISpace = keyof typeof STITCHES_CONFIG.tokens.space;

// inside the utilities of the STITCHES_CONFIG

calcMultiply: utilCss => (
  ...values: ISpace[],
) => utilCss.string`calc(${values.join(' * ')})`
```

What do you think? :)

**Comment by christianalfoni** [comment]
Hi @CodingDive ,

Interesting, though it changes the nature of the API. But I am curious... what are the limitations of just using calc now? Like `css.marginTop('calc(12px  + 14px)')`? You want to combine it with tokens? 

A different way to approach it would be:

```ts
css.marginTop((tokens) => `calc(${tokens.A} + ${tokens.B}`)
```

Though calc is not a typical thing to use, so having a hard time defending a change to the API just to support that especially, hm

**Comment by CodingDive** [comment]
I'm happy with `css.marginTop('calc(12px + 14px)')`. I did want to ideally have a typed interface and use it with tokens but since it's such a rare occurence, I'm fine with putting calc into strings.
