### ISSUE TITLE
Error in @stitches/tailwind Documentation (wrong import of createCss)

### ISSUE THREAD

**Issue by Suniron** [christianalfoni/stitches#30]
This is mentionned in `Configure` section of stitches/tailwind:
`import {createCss} from @stiches/styled` instead of `@stitches/css`, right ?

Capture:
![image](https://user-images.githubusercontent.com/36677774/81350398-1fé376280-90c2-11ea-8e11-9676b1ed5dfd.png)

**Comment by christianalfoni** [comment]
Ah, yes, fixed 😄
