### ISSUE TITLE
Stitches CSS+STYLED+TAILWIND not work with NextJS 9.4 upgrade (The propety "prototype" is not available")

### ISSUE THREAD

**Issue by Suniron** [christianalfoni/stitches#32]
Hi,

I'm tried to upgrade NextJS from 9.3.x to 9.4 and i see the error bellow:
![photo_2020-05-16_18-50-54](https://user-images.githubusercontent.com/36677774/82125559-1243fe80-97a7-11ea-93cd-c8b8d69b1de8.jpg)

I use Stitches CSS+TAILWIND+STYLED in my projet (with typescript) .

Thanks by advance :-).

For now, i stay with NextJS 9.3.x

**Comment by christianalfoni** [comment]
I saw you found a solution to this on Discord? What was the issue? Just do document 😄

**Comment by Suniron** [comment]
Thank's, it's now fixed !!! :-D
