### ISSUE TITLE
styled prop and variants leaking to the element

### ISSUE THREAD

**Issue by rubenmoya** [christianalfoni/stitches#36]
Hello! I've been checking out the "real time theming" demo in Codesandbox and after inspecting the elements I've realised we're adding invalid attributes to the elements:

![image](https://user-images.githubusercontent.com/905225/86742882-bc6a3500-c038-11ea-8174-3c4984d9be79.png)

See the `usage` and `styled` attributes. We should filter those somehow.

Not sure how difficult it would be but I'd love to tackle this issue :)

**Comment by peduarte** [comment]
Done https://github.com/christianalfoni/stitches/commit/33c426a8720dda11cfc629eee04c9832e382dfe3

**Comment by peduarte** [comment]
@rubenmoya feel free to close 👍
