### ISSUE TITLE
Type assistance for non system-ui properties

### ISSUE THREAD

**Issue by CodingDive** [christianalfoni/stitches#4]
The type support seems great for the `system-ui` properties that we are configuring ourselves. Is there a way to achieve the same thing for `display`, `alignItems` and all the other css properties?

![image](https://user-images.githubusercontent.com/28842311/79619851-58596400-810e-11ea-9df3-48f37254a9df.png)

**Comment by christianalfoni** [comment]
Hi @CodingDive !

I did some research on this, it is actually how Typescript works, which is sad and we should find a workaround. Here is the thread: https://github.com/Microsoft/TypeScript/issues/29729#issuecomment-471566609

It is really weird though, cause I did have the types at some point.... hm. 

Though to improve typing speed I am considering just running our own typing for CSS

**Comment by christianalfoni** [comment]
Okay, so I think we just need to follow up on this ourselves, I changed the typing so we get full control. Fixed in new release coming now 😄
