### ISSUE TITLE
`SecurityError` when doing SSR with Next.js

### ISSUE THREAD

**Issue by biowaffeln** [christianalfoni/stitches#55]
Hi!

I ran into an issue when I tried to use stitches with Next.js. Here are the steps to reproduce:

1. install the `stitches-css` starter from the Next.js examples
2. try to load an external stylesheet by adding the following code to `_document.js`:
```js
  import Document, { Html, Head, Main, NextScript } from "next/document";
  ...

  render() {
    return (
      <Html>
        <Head>
          <link
            href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
            rel="stylesheet"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }

```

3. get the following error (in Chrome):

```
SecurityError: Failed to execute 'insertRule' on 'CSSStyleSheet': Cannot access StyleSheet to insertRule
createCss
./node_modules/@stitches/css/es/index.js:183
```

It looks like [something like this](https://stackoverflow.com/a/49101538) is the problem - maybe the insertRule order is off when there's already existing stylesheets?

**Comment by peduarte** [comment]
Im pretty sure this was fixed in the latest release. Which version you on?

**Comment by biowaffeln** [comment]
Yep you're right @peduarte, the version in the Next.js was 3.0.2, once I upgraded it to 5.0.0 the problem went away. Thanks!
