### ISSUE TITLE
Data selectors

### ISSUE THREAD

**Issue by CodingDive** [christianalfoni/stitches#7]
Hey, are there some plans to support data-selectors?

Maybe the second argument could be fallback to a selector if no fitting `pseudo` class is found.

This would be immensely helpful for styling libraries that primarily use `data-selectors` to adjust the styles of their components. E.g [reach-ui](https://reacttraining.com/reach-ui/menu-button#menuitem-css-selectors) does this quite a lot.

**Comment by christianalfoni** [comment]
Hi @CodingDive ,

You can actually use the pseudo selectors for this:

```ts
css.color('red', '[attr...]')
```

It is literarily the stuff between the classname and the starting `{` of the rule 😄 

Does it work?
